services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dvc\ContaoFormFieldExtensionsBundle\:
    resource: ../../
    exclude:
      - ../../ContaoManager
      - ../../DependencyInjection
      - ../../DvcContaoFormFieldExtensionsBundle.php
